# Generated by Django 4.0.4 on 2022-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lotteryimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotteryimage1', models.ImageField(blank=True, upload_to='ColorGameApp/images/')),
                ('lotteryimage2', models.ImageField(blank=True, upload_to='ColorGameApp/images/')),
                ('lotteryimage3', models.ImageField(blank=True, upload_to='ColorGameApp/images/')),
                ('lotteryimage4', models.ImageField(blank=True, upload_to='ColorGameApp/images/')),
            ],
        ),
    ]
