# Generated by Django 4.0.4 on 2022-06-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryimages',
            name='lotteryimagegif1',
            field=models.ImageField(blank=True, upload_to='ColorGameApp/images/'),
        ),
        migrations.AddField(
            model_name='lotteryimages',
            name='lotteryimagegif2',
            field=models.ImageField(blank=True, upload_to='ColorGameApp/images/'),
        ),
        migrations.AddField(
            model_name='lotteryimages',
            name='lotteryimagegif3',
            field=models.ImageField(blank=True, upload_to='ColorGameApp/images/'),
        ),
        migrations.AddField(
            model_name='lotteryimages',
            name='lotteryimagegif4',
            field=models.ImageField(blank=True, upload_to='ColorGameApp/images/'),
        ),
    ]
