# Generated by Django 3.0.3 on 2022-06-30 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ColorGameApp', '0002_lotteryimages_lotteryimagegif1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryimages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('walletBalance', models.CharField(blank=True, max_length=7, null=True)),
                ('username', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='upiDetails',
            fields=[
                ('upiId', models.AutoField(primary_key=True, serialize=False)),
                ('upi', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='bankDetails',
            fields=[
                ('bankId', models.AutoField(primary_key=True, serialize=False)),
                ('ifsc', models.CharField(blank=True, max_length=20)),
                ('accountNumber', models.CharField(blank=True, max_length=20)),
                ('recipientName', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.user')),
            ],
        ),
    ]
