# Generated by Django 3.0.3 on 2022-06-30 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0003_auto_20220630_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameDetails',
            fields=[
                ('gameId', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('group', models.CharField(blank=True, max_length=5)),
                ('number', models.CharField(blank=True, max_length=5)),
                ('contractMoney', models.CharField(blank=True, max_length=7)),
                ('tickets', models.CharField(blank=True, max_length=5)),
                ('totalcontractMoney', models.CharField(blank=True, max_length=7)),
                ('user', models.ForeignKey(blank=True, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.user')),
            ],
        ),
    ]
