# Generated by Django 3.0.3 on 2022-07-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0004_gamedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='time',
            field=models.TimeField(),
        ),
    ]
