# Generated by Django 3.0.3 on 2022-07-01 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0005_auto_20220701_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
