# Generated by Django 3.0.3 on 2022-07-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0008_auto_20220701_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='time',
            field=models.TimeField(blank=True, editable=False),
        ),
    ]
