# Generated by Django 3.0.3 on 2022-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0009_auto_20220702_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
