# Generated by Django 3.0.3 on 2022-07-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0011_auto_20220704_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False)),
                ('groppName', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.group'),
        ),
    ]
