# Generated by Django 3.0.3 on 2022-07-05 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0012_auto_20220705_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='groppName',
            new_name='groupName',
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('resultId', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.group')),
            ],
        ),
    ]
