# Generated by Django 3.0.3 on 2022-07-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0013_auto_20220705_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetails',
            name='resultId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.results'),
        ),
    ]
