# Generated by Django 3.0.3 on 2022-07-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0015_results_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.group'),
        ),
    ]
