# Generated by Django 4.0.3 on 2022-07-09 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ColorGameApp', '0019_remove_user_walletbalance_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='accountNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='recipientName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='contractMoney',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.group'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='tickets',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='totalcontractMoney',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='user',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.user'),
        ),
        migrations.AlterField(
            model_name='results',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='results',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.group'),
        ),
        migrations.AlterField(
            model_name='results',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='results',
            name='result',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='results',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upidetails',
            name='upi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='upidetails',
            name='user',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.user'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='walletBalance',
            field=models.CharField(max_length=7),
        ),
    ]
