# Generated by Django 4.0.3 on 2022-07-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0021_alter_bankdetails_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.user'),
        ),
        migrations.AlterField(
            model_name='upidetails',
            name='user',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='ColorGameApp.user'),
        ),
    ]
