# Generated by Django 4.0.3 on 2022-07-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ColorGameApp', '0025_auto_20220714_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lotteryimages',
        ),
    ]
